# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "pg_ts_cfg", :id => false, :force => true do |t|
    t.column "ts_name",  :text, :null => false
    t.column "prs_name", :text, :null => false
    t.column "locale",   :text
  end

  create_table "pg_ts_cfgmap", :id => false, :force => true do |t|
    t.column "ts_name",   :text,                  :null => false
    t.column "tok_alias", :text,                  :null => false
    t.column "dict_name", :string, :limit => nil
  end

# Could not dump table "pg_ts_dict" because of following StandardError
#   Unknown type 'regprocedure' for column 'dict_init', yaml: #<ActiveRecord::ConnectionAdapters::Column:0x343b8b0 @limit=nil, @name="dict_init", @null=true, @primary=nil, @default=nil, @scale=nil, @sql_type="regprocedure", @type=nil, @precision=nil>, types: {:boolean=>{:name=>"boolean"}, :timestamp=>{:name=>"timestamp"}, :decimal=>{:name=>"decimal"}, :float=>{:name=>"float"}, :integer=>{:name=>"integer"}, :date=>{:name=>"date"}, :text=>{:name=>"text"}, :primary_key=>"serial primary key", :datetime=>{:name=>"timestamp"}, :binary=>{:name=>"bytea"}, :time=>{:name=>"time"}, :string=>{:name=>"character varying", :limit=>255}} 

# Could not dump table "pg_ts_parser" because of following StandardError
#   Unknown type 'regprocedure' for column 'prs_start', yaml: #<ActiveRecord::ConnectionAdapters::Column:0x3433944 @limit=nil, @name="prs_start", @null=false, @primary=nil, @default=nil, @scale=nil, @sql_type="regprocedure", @type=nil, @precision=nil>, types: {:boolean=>{:name=>"boolean"}, :timestamp=>{:name=>"timestamp"}, :decimal=>{:name=>"decimal"}, :float=>{:name=>"float"}, :integer=>{:name=>"integer"}, :date=>{:name=>"date"}, :text=>{:name=>"text"}, :primary_key=>"serial primary key", :datetime=>{:name=>"timestamp"}, :binary=>{:name=>"bytea"}, :time=>{:name=>"time"}, :string=>{:name=>"character varying", :limit=>255}} 

# Could not dump table "rss_entries" because of following StandardError
#   Unknown type 'tsvector' for column 'vectors', yaml: #<ActiveRecord::ConnectionAdapters::Column:0x342c02c @limit=nil, @name="vectors", @null=true, @primary=nil, @default=nil, @scale=nil, @sql_type="tsvector", @type=nil, @precision=nil>, types: {:boolean=>{:name=>"boolean"}, :timestamp=>{:name=>"timestamp"}, :decimal=>{:name=>"decimal"}, :float=>{:name=>"float"}, :integer=>{:name=>"integer"}, :date=>{:name=>"date"}, :text=>{:name=>"text"}, :primary_key=>"serial primary key", :datetime=>{:name=>"timestamp"}, :binary=>{:name=>"bytea"}, :time=>{:name=>"time"}, :string=>{:name=>"character varying", :limit=>255}} 

end
