# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "pg_ts_cfg", :id => false, :force => true do |t|
    t.column "ts_name",  :text, :null => false
    t.column "prs_name", :text, :null => false
    t.column "locale",   :text
  end

  create_table "pg_ts_cfgmap", :id => false, :force => true do |t|
    t.column "ts_name",   :text,                  :null => false
    t.column "tok_alias", :text,                  :null => false
    t.column "dict_name", :string, :limit => nil
  end

  create_table "pg_ts_dict", :id => false, :force => true do |t|
    t.column "dict_name",       :text,                  :null => false
    t.column "dict_init",       :string, :limit => nil
    t.column "dict_initoption", :text
    t.column "dict_lexize",     :string, :limit => nil, :null => false
    t.column "dict_comment",    :text
  end

  create_table "pg_ts_parser", :id => false, :force => true do |t|
    t.column "prs_name",      :text,                  :null => false
    t.column "prs_start",     :string, :limit => nil, :null => false
    t.column "prs_nexttoken", :string, :limit => nil, :null => false
    t.column "prs_end",       :string, :limit => nil, :null => false
    t.column "prs_headline",  :string, :limit => nil, :null => false
    t.column "prs_lextype",   :string, :limit => nil, :null => false
    t.column "prs_comment",   :text
  end

  create_table "rss_entries", :force => true do |t|
    t.column "title",   :string
    t.column "summary", :text
    t.column "link",    :string
    t.column "vectors", :string, :limit => nil
  end

end
